### PR TITLE
Improve glade example with import_str and add an action to the button

### PR DESCRIPTION
**Pull request by pd40**
running builder_basics required the glade file in the current directory. Use import_str to load it at compile time. Also add a basic dialog on button press.

### CODE REVIEW

**Comment by gkoz** [comment]
Looks like a very nice improvement!
The commits should probably be squashed or the addition of the message dialog moved to the second commit.

**Comment by gkoz** [comment]
Oh, the branch. @GuillaumeGomez there's an issue that we'll either have to cherry-pick this into the `pending` branch or ask to reopen the PR against that branch. Possibly make use of https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by GuillaumeGomez** [comment]
Hum... I think it would be better to reopen the PR. Do you want to write the `CONTRIBUTING.md` file or should I ?

**Comment by gkoz** [comment]
@GuillaumeGomez You should probably do that, so you'd immediately see if github has picked up that file correctly.

@pd40 Would you please reopen this PR targeting the `pending` branch?

**Comment by GuillaumeGomez** [comment]
Ok, I'll do it tomorrow then.

**Comment by pd40** [comment]
Will do. Thanks for taking a look.

**Pull request closed without merging**
