### PR TITLE
Add cairo_threads -- my attempt at multi-threaded drawing

### PR DESCRIPTION
**Pull request by gkoz**
I'm favoring correctness over performance here. This could probably be done less safely but more efficiently.

### CODE REVIEW

**Comment by gkoz** [comment]
cc @lucaswerkmeister @mikhail-m1

**Comment by GuillaumeGomez** [comment]
Weird error. I guess this is on appveyor ?

**Comment by gkoz** [comment]
Yeah, maybe crates.io was down or something.

**Comment by GuillaumeGomez** [comment]
Doesn't matter, it's merged. Thanks ! :)

**Pull request merged**
