### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by GuillaumeGomez** [comment]
cc @pnkfelix

**Comment by gkoz** [comment]
Looks good. We'll probably want to set the default branch to `crate` [here](https://github.com/rust-gnome/examples/settings) so people would not assume that we want them to use git dependencies.

**Comment by GuillaumeGomez** [comment]
It would be the opposite of all other repos. So as you prefer.

**Comment by gkoz** [comment]
As there's no other distribution channel for binary crates, I don't see any way around it: new users should see the preferred version and there might be a message for contributors somewhere -- that you need to open PRs against `master`.

**Comment by GuillaumeGomez** [comment]
I'll do it that way. I'll also update crates.

**Comment by gkoz** [comment]
Keeping the crates dependency?

**Comment by GuillaumeGomez** [comment]
I created a non-crate branch. Take a look! :-)

**Pull request closed without merging**
